# TODO actually write this file
# A container for Microblog
# 	bind mount to .env 
#	boot script to start gunicorn 
# A container for Elasticsearch 
#	named mount for wherever Elasticsearch keeps data
# A container for MySQL
# 	bind mount for init scripts
# 	named mount for /var/lib data
# A container for LibreTranslate ? 
# A container for Redis
# A container for rq worker
#	this container uses the same image as microblog, but instead of 
# 	starting gunicorn, it starts rq worker, because the environment
# 	variables told it to

