# A docker compose file for Miguel Grinberg's Microblog demo system.
# 
# Remember to set the .env file, see the README.md and .env.example
# No need to load the .env file during the `docker compose up` command.

# - Run Notes -----------------------------------------
#
# To run, `cd` into the directory containing the `docker-compose.yml` file,
# and:
# 1) `docker compose up`

services:
  mysql:
    image: mysql:latest
#    ports:
#      - 3306:3306
    volumes:
      - microblog-sql-data:/var/lib/mysql
#      - "./init-microblog.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
#      - MYSQL_ROOT_PASSWORD=m1crob10g
      - MYSQL_ONETIME_PASSWORD=yes
      - MYSQL_USER=microblog
      - MYSQL_PASSWORD=micR0-blog-miguel
      - MYSQL_DATABASE=microblog

  redis:
    image: redis:latest
#    ports:
#      - 6379:6379
    volumes:
      - microblog-redis-data:/data

  # :latest tag doesn't exist for elasticsearch...must specify a version
  elasticsearch:
    image: elasticsearch:8.4.0
#    ports:
#      - 9200:9200
    volumes:
      - microblog-elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  libretranslate:
    image: libretranslate/libretranslate:latest
#    ports:
#      - 81:81
    environment:
      - LT_PORT=81
      - LT_HOST=0.0.0.0

  microblog:
    image: ultasun/microblog:latest
    depends_on:
      - "libretranslate"
      - "mysql"
      - "elasticsearch"
      - "redis"
    ports:
      - 80:5000
    volumes:
      - "./.env:/app/.env"

  microblog-rq:
    image: ultasun/microblog:latest
    depends_on:
      - "redis"
    environment:
      - MICROBLOG_RQ_WORKER_MODE=yes
    volumes:
      - "./.env:/app/.env"
    
volumes:
  microblog-sql-data:
  microblog-redis-data:
  microblog-elasticsearch-data:

    
