"""add language field to posts

Revision ID: 08533506eb62
Revises: be59036a8f81
Create Date: 2022-09-05 14:11:54.669945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08533506eb62'
down_revision = 'be59036a8f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
