"""added new fields in the user model

Revision ID: 708079d2f28b
Revises: a3278fd15dcd
Create Date: 2022-09-02 02:19:48.396439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708079d2f28b'
down_revision = 'a3278fd15dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
