"""added user tokens for the API blueprint

Revision ID: 734103acdbd0
Revises: 099e60c68bf2
Create Date: 2022-09-08 04:21:57.497650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734103acdbd0'
down_revision = '099e60c68bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
